-- MySQL Script generated by MySQL Workbench
-- mar. 19 avril 2022 11:13:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SMMediaBdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SMMediaBdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SMMediaBdd` ;
USE `SMMediaBdd` ;

-- -----------------------------------------------------
-- Table `SMMediaBdd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SMMediaBdd`.`users` (
  `idUsers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(75) NOT NULL,
  `prenom` VARCHAR(75) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL DEFAULT 'utilisateur',
  `mdp` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(250) NOT NULL,
  `ville` VARCHAR(100) NOT NULL,
  `CP` INT(5) NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SMMediaBdd`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SMMediaBdd`.`categorie` (
  `idCategorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SMMediaBdd`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SMMediaBdd`.`article` (
  `idArticle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(250) NOT NULL,
  `genre` VARCHAR(100) NOT NULL,
  `auteur` VARCHAR(100) NOT NULL,
  `collection` VARCHAR(100) NOT NULL,
  `editeur` VARCHAR(100) NOT NULL,
  `emprunt` TINYINT NOT NULL DEFAULT 'non',
  `date_pret` TIMESTAMP NULL,
  `file` VARCHAR(250) NULL,
  `categorie_idCategorie` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_article_categorie1_idx` (`categorie_idCategorie` ASC) VISIBLE,
  CONSTRAINT `fk_article_categorie1`
    FOREIGN KEY (`categorie_idCategorie`)
    REFERENCES `SMMediaBdd`.`categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SMMediaBdd`.`pret`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SMMediaBdd`.`pret` (
  `idPret` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_idUsers` INT UNSIGNED NOT NULL,
  `article_idArticle` INT UNSIGNED NOT NULL,
  `date_depart` TIMESTAMP NULL,
  `date_retour` TIMESTAMP NULL,
  PRIMARY KEY (`idPret`),
  INDEX `fk_pret_users_idx` (`users_idUsers` ASC) VISIBLE,
  INDEX `fk_pret_article1_idx` (`article_idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_pret_users`
    FOREIGN KEY (`users_idUsers`)
    REFERENCES `SMMediaBdd`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pret_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `SMMediaBdd`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SMMediaBdd`.`historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SMMediaBdd`.`historique` (
  `idHistorique` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pret_idPret` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idHistorique`),
  INDEX `fk_historique_pret1_idx` (`pret_idPret` ASC) VISIBLE,
  CONSTRAINT `fk_historique_pret1`
    FOREIGN KEY (`pret_idPret`)
    REFERENCES `SMMediaBdd`.`pret` (`idPret`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
